apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: echo
spec:
  traffic: # setting for byo name revision
  - latestRevision: true
    percent: 100
  template:
    metadata:
      name: echo-rev1
    # metadata:
    #   annotations:
    #     serving.knative.dev/checkValidityOnDeploy: "false"
    spec:
      containers:
        - image: duglin/echo
          env:
            - name: CRASH1
              value: bar
