apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: echo-10
spec:
  traffic: # setting for byo name revision
  - latestRevision: true
    percent: 100
  template:
    # metadata:
    #   name: echo-test-0107-rev1
    metadata:
      annotations:
        autoscaling.knative.dev/initialScale: "10"
        autoscaling.knative.dev/minScale: "20"
        autoscaling.knative.dev/targetUtilizationPercentage: "1"
    spec:
      containerConcurrency: 1
      containers:
        - image: duglin/echo
          env:
            - name: CRASH1
              value: bar
