apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-go
  namespace: serving-tests
spec:
  template:
    spec:
      containers:
        - image: docker.io/taragu/helloworld-go-private
          env:
            - name: TARGET
              value: "Go Sample v1"
          # volumeMounts:
          #   - mountPath: /etc/db-user
          #     name: db-user-pass
          #     readOnly: true
      imagePullSecrets:
        - name: regcred-serving-tests
      # volumes:
      #   - name: db-user-pass
      #     secret:
      #       secretName: db-user-pass-invalid
