apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: echo
spec:
  template:
    metadata:
      name: echo-v2
    spec:
      containers:
        - image: taragu/helloworld-go
  traffic:
  - latestRevision: true
    percent: 50
    tag: new
  - revisionName: echo-v1
    percent: 50
    tag: old
