apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-crash
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/taragu/helloworld-crash
          env:
            - name: TARGET
              value: "Go Sample v1"
